tunnel: smartsense-dashboard
credentials-file: /home/ramon/.cloudflared/875177a4-403c-4fba-8c45-f0febd936687.json

ingress:
  - hostname: dashboard.smartsenseia.org
    service: http://127.0.0.1:8000

  - hostname: api.smartsenseia.org
    service: http://127.0.0.1:8000

  - service: http_status:404



